### ISSUE TITLE
Remove all hotlinking

### ISSUE THREAD

**Issue by hymccord** [MHCommunity/mhbasics#32]
Posting here so we can track it.

[Hotlinking](https://simple.wikipedia.org/wiki/Hotlinking) is considered bad practice.

Image assets should be stored locally and the image srcs updated.
Find offenders by searching for `src="https://www.mousehuntgame.com` in your favorite editor.

**Comment by kuhmann** [comment]
good point, we've reached out and received the blessing from devs, Mellon will fix it in #30 . Thanks for bringing it up!
